# doc: https://grafana.com/docs/loki/v3.1.x/configure/
# examples: https://grafana.com/docs/loki/v3.1.x/configure/examples/configuration-examples/
# checkout: https://gist.github.com/Xe/c3c786b41ec2820725ee77a7af551225

auth_enabled: false
analytics:
  reporting_enabled: false

server:
  http_listen_port: 3030

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
  - from: 2020-05-15
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

storage_config:
  filesystem:
    directory: /tmp/loki/chunks




# server:
#   http_listen_port: 3030 # 3100
#   grpc_listen_port: 3031 # 9096
#   log_level: info
#   grpc_server_max_concurrent_streams: 1000

# common:
#   instance_addr: 127.0.0.1
#   path_prefix: /tmp/loki
#   storage:
#     filesystem:
#       chunks_directory: /tmp/loki/chunks
#       rules_directory: /tmp/loki/rules
#   replication_factor: 1
#   ring:
#     kvstore:
#       store: inmemory

# query_range:
#   results_cache:
#     cache:
#       embedded_cache:
#         enabled: true
#         max_size_mb: 100

# schema_config:
#   configs:
#     - from: 2020-10-24
#       store: tsdb
#       object_store: filesystem
#       schema: v13
#       index:
#         prefix: index_
#         period: 24h

# pattern_ingester:
#   enabled: true

# metric_aggregation:
#     enabled: true
#     loki_address: localhost:3030

# ruler:
#   alertmanager_url: http://localhost:9093

# frontend:
#   encoding: protobuf
