# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/42a21b7a-b642-4d86-98b5-eeb59a0201ee";
      fsType = "btrfs";
      options = [ "subvol=__active/root" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4E22-744E";
      fsType = "vfat";
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/42a21b7a-b642-4d86-98b5-eeb59a0201ee";
      fsType = "btrfs";
      options = [ "subvol=__active/var" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/42a21b7a-b642-4d86-98b5-eeb59a0201ee";
      fsType = "btrfs";
      options = [ "subvol=__active/home" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/42a21b7a-b642-4d86-98b5-eeb59a0201ee";
      fsType = "btrfs";
      options = [ "subvol=__active/tmp" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/cabdb1c4-ceb2-4a50-b455-1070f4159d9a"; }
    ];

  nix.maxJobs = lib.mkDefault 1;
  virtualisation.virtualbox.guest.enable = true;
}
