{
 "title": "nginx",
 "description": "A version of the NGINX dashboard, specific to the onboarding training exercise",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Requests per status code",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (statuscode) (count_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"HTTP/1.1\\\" (?P<statuscode>\\\\d{3}) \"[$__interval]))"
    }
   ]
  },
  {
   "title": "Total requests  ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({filename=\"/var/log/nginx/access.log\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({filename=\"/var/log/nginx/access.log\"} | regexp `HTTP\\/1\\.1\" (?P<statuscode>\\d{3}) (?P<value>\\d+) (?P<refferer>\".*?\") \"(?P<useragent>.*)\"` [5m])"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (statuscode) (count_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"HTTP/1.1\\\" (?P<statuscode>\\\\d{3}) \"[$__interval]))"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(host) (count_over_time({filename=\"/var/log/nginx/access.log\"} | regexp `HTTP\\/1\\.1\" (?P<statuscode>\\d{3}) (?P<value>\\d+) (?P<refferer>\".*?\") \"(?P<useragent>.*)\"` [$__interval]))"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "topk(5, sum by (ipaddress) (count_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"(?P<ipaddress>\\\\d{1,3}\\\\.\\\\d{1,3}\\\\.\\\\d{1,3}\\\\.\\\\d{1,3})\"[$__interval])))"
    }
   ]
  },
  {
   "title": "Top Requested Pages",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk(5, sum by(path) (rate({filename=\"/var/log/nginx/access.log\"} | regexp `[GET|POST] (?P<path>.*?) HTTP` [$__auto])))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/nginx/access.log\"}"
    }
   ]
  },
  {
   "title": "Top User Agents",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "topk(10, sum by (useragent) (count_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"HTTP\\\\/1\\\\.1\\\" (?P<statuscode>\\\\d{3}) (?P<bytessent>\\\\d+) (?P<refferer>\\\".*?\\\") \\\"(?P<useragent>.*)\\\"\"[$__interval])))"
    }
   ]
  },
  {
   "title": "Referrer",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "topk(5, sum by (refferer) (count_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"HTTP\\\\/1\\\\.1\\\" (?P<statuscode>\\\\d{3}) (?P<bytessent>\\\\d+) (?P<refferer>\\\".*?\\\") \\\"(?P<useragent>.*)\\\"\"[$__interval])))"
    }
   ]
  }
 ]
}