#save_to_clipboard = true

[colors.normal]
black = "0x01060E"
blue = "0x53BDFA"
cyan = "0x00B9EB"
green = "0x54FF54"
magenta = "0xAD0096"
red = "0xEA6C73"
white = "0xC7C7C7"
yellow = "0xF9AF4F"

[colors.primary]
background = "0x000000"
foreground = "0x00D10A"

[font]
size = 10

[font.normal]
family = "Bitstream Vera Sans Mono"
style = "Regular"

# [schemes.solarized_dark.bright]
# black = "0x696969"
# blue = "0x007FFF"
# cyan = "0x00CCCC"
# green = "0x03C03C"
# magenta = "0xFF1493"
# red = "0xFF2400"
# white = "0xFFFAFA"
# yellow = "0xFDFF00"

# [schemes.solarized_dark.normal]
# black = "0x10100E"
# blue = "0x0087BD"
# cyan = "0x20B2AA"
# green = "0x009F6B"
# magenta = "0x9A4EAE"
# red = "0xC40233"
# white = "0xC6C6C4"
# yellow = "0xFFD700"

# [schemes.solarized_dark.primary]
# background = "0x10100E"
# foreground = "0xC6C6C4"

# [schemes.solarized_rip.normal]
# black = "0x01060E"
# blue = "0x53BDFA"
# cyan = "0x00B9EB"
# green = "0x54FF54"
# magenta = "0xAD0096"
# red = "0xEA6C73"
# white = "0xC7C7C7"
# yellow = "0xF9AF4F"

# [schemes.solarized_rip.primary]
# background = "0x000000"
# foreground = "0x00D10A"

[shell]
args = ["bash"]
program = "/usr/bin/env"
